[build]
  command = "npx nx run customer-loyalty-rewards:build --configuration=production"
  publish = "dist/apps/customer-loyalty-rewards"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200